const state={products:[],cart:JSON.parse(localStorage.getItem('mt_cart')||'[]')};
function saveCart(){localStorage.setItem('mt_cart',JSON.stringify(state.cart));updateCartCount();}
function updateCartCount(){const c=state.cart.reduce((a,i)=>a+i.qty,0);document.querySelectorAll('[data-cart-count]').forEach(e=>e.textContent=c);}
async function loadProducts(){const r=await fetch('data/products.json');state.products=await r.json();return state.products;}
function formatPrice(p,c='EUR'){try{return new Intl.NumberFormat('fr-FR',{style:'currency',currency:c}).format(p);}catch{return p.toFixed(2)+' €';}}
async function renderGrid(sel='#grid'){await loadProducts();const g=document.querySelector(sel);if(!g)return;g.innerHTML=state.products.map(p=>`
<a class="card" href="product.html?id=${encodeURIComponent(p.id)}"><img src="${p.thumbnail}" alt="${p.name}"><div class="info"><div>${p.category}</div><div class="kufi">${p.name}</div><div class="price">${formatPrice(p.price,p.currency)}</div></div></a>`).join('');}
async function renderPDP(){await loadProducts();const id=new URLSearchParams(location.search).get('id');const p=state.products.find(x=>x.id===id);if(!p)return;document.querySelector('[data-breadcrumb-name]').textContent=p.name;document.querySelector('[data-name]').textContent=p.name;document.querySelector('[data-price]').textContent=formatPrice(p.price,p.currency);document.querySelector('[data-desc]').textContent=p.description;document.querySelector('[data-meta]').innerHTML=`
<tr><th>Catégorie</th><td>${p.category}</td></tr><tr><th>Métal</th><td>${p.metal}</td></tr><tr><th>Émail</th><td>${p.enamel_color}</td></tr><tr><th>Stock</th><td>${p.stock}</td></tr>`;document.querySelector('[data-gallery]').innerHTML=p.images.map(s=>`<img src="${s}" alt="${p.name}">`).join('');const b=document.querySelector('[data-add]');b.addEventListener('click',()=>{const q=Math.max(1,parseInt(document.querySelector('[data-qty]').value||'1',10));const e=state.cart.find(i=>i.id===p.id);if(e)e.qty+=q;else state.cart.push({id:p.id,name:p.name,price:p.price,currency:p.currency,thumbnail:p.thumbnail,qty:q});saveCart();b.textContent='Ajouté ✓';setTimeout(()=>b.textContent='Ajouter au panier',1200);});}
async function renderCart(){await loadProducts();const c=document.querySelector('[data-cart]');const t=document.querySelector('[data-total]');if(!c)return;c.innerHTML='';let total=0;state.cart.forEach((item,idx)=>{const line=item.price*item.qty;total+=line;const row=document.createElement('div');row.className='cart-item';row.innerHTML=`
<img src="${item.thumbnail}" alt="${item.name}"><div><div class="kufi">${item.name}</div><div class="muted">${formatPrice(item.price,item.currency)} × <input type="number" min="1" value="${item.qty}" style="width:64px" data-qty-input></div></div><div><div>${formatPrice(line,item.currency)}</div><button class="btn" data-remove>&times;</button></div>`;row.querySelector('[data-qty-input]').addEventListener('change',e=>{const v=Math.max(1,parseInt(e.target.value||'1',10));state.cart[idx].qty=v;saveCart();renderCart();});row.querySelector('[data-remove]').addEventListener('click',()=>{state.cart.splice(idx,1);saveCart();renderCart();});c.appendChild(row);});t.textContent=formatPrice(total);} 
document.addEventListener('DOMContentLoaded',()=>{updateCartCount();if(document.body.dataset.page==='home')renderGrid('#homeGrid');if(document.body.dataset.page==='shop')renderGrid('#grid');if(document.body.dataset.page==='pdp')renderPDP();if(document.body.dataset.page==='cart')renderCart();});